name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build Binary
        run: flutter build apk --build-name=1.0.0 --build-number=${{ github.run_number }} --release
      - name: Change File Name
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/FlutterChart-${{ github.run_number }}.apk
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/app/outputs/flutter-apk/*.apk